package me.rkfg.ns2gather.dto;

public enum MessageType {
    USER_ENTERS, USER_LEAVES, CHAT_MESSAGE, USER_READY, USER_UNREADY, GAME_START, VOTE_CHANGE, VOTE_ENDED, GATHER_STATUS, USER_KICKED, RUN_TIMER, STOP_TIMER, MORE_PLAYERS
}
